output "server_id" {
  description = "PostgreSQL Flexible Server ID."
  value       = azurerm_postgresql_flexible_server.this.id
}

output "server_name" {
  description = "PostgreSQL Flexible Server name."
  value       = azurerm_postgresql_flexible_server.this.name
}

output "fqdn" {
  description = "Fully qualified domain name of the server."
  value       = azurerm_postgresql_flexible_server.this.fqdn
}

output "administrator_login" {
  description = "Administrator login name."
  value       = azurerm_postgresql_flexible_server.this.administrator_login
}

output "administrator_password" {
  description = "Administrator password when generated by the module."
  value       = try(random_password.admin[0].result, var.administrator_password)
  sensitive   = true
}

output "private_dns_zone_id" {
  description = "Private DNS zone ID when created or referenced."
  value       = local.private_dns_zone_id
}

output "database_ids" {
  description = "Database resource IDs keyed by logical name."
  value       = { for name, db in azurerm_postgresql_flexible_server_database.this : name => db.id }
}
