locals {
  managed_secret = coalesce(
    try(azurerm_key_vault_secret.this[0], null),
    try(azurerm_key_vault_secret.this_external[0], null),
    azurerm_key_vault_secret.shell[0]
  )
}

output "secret_id" {
  description = "ID of the Key Vault secret."
  value       = local.managed_secret.id
}

output "secret_name" {
  description = "Name of the Key Vault secret."
  value       = local.managed_secret.name
}

output "secret_version" {
  description = "Version of the Key Vault secret."
  value       = local.managed_secret.version
}

output "secret_resource_id" {
  description = "Full Azure resource ID of the secret."
  value       = local.managed_secret.resource_id
}

output "key_vault_id" {
  description = "ID of the Key Vault containing the secret."
  value       = local.key_vault_id
}

output "random_password_generated" {
  description = "Whether the secret value was generated by Terraform."
  value       = var.generate_random_password != null
}

output "secret_value_managed" {
  description = "Whether Terraform manages the secret value."
  value       = var.generate_random_password != null || nonsensitive(var.secret_value != null)
}
